all: alwaysinstallelevated	autologon	credentialmanager	hijackablepath	modifiableautorun	tokenprivileges	unquotedsvcpath

alwaysinstallelevated: alwaysinstallelevated.c
	x86_64-w64-mingw32-gcc -c alwaysinstallelevated.c -o alwaysinstallelevated.o


autologon: autologon.c
	x86_64-w64-mingw32-gcc -c autologon.c -o autologon.o


credentialmanager: credentialmanager.c
	x86_64-w64-mingw32-gcc -c credentialmanager.c -o credentialmanager.o


hijackablepath: hijackablepath.c
	x86_64-w64-mingw32-gcc -c hijackablepath.c -o hijackablepath.o


modifiableautorun: modifiableautorun.c
	x86_64-w64-mingw32-gcc -c modifiableautorun.c -o modifiableautorun.o


tokenprivileges: tokenprivileges.c
	x86_64-w64-mingw32-gcc -c tokenprivileges.c -o tokenprivileges.o


unquotedsvcpath: unquotedsvcpath.c
	x86_64-w64-mingw32-gcc -c unquotedsvcpath.c -o unquotedsvcpath.o